pipeline:
  identifier: Build_magdamana001_DG2_1706190666248
  name: Build DG2
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706190650995
        repoName: magdamana001/DG2
  stages:
    - stage:
        name: Build2
        identifier: Build2
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      name: B2
                      identifier: B2
                      template:
                        templateRef: as
                        versionLabel: "1"
                  - step:
                      name: s2
                      identifier: s2
                      template:
                        templateRef: as
                        versionLabel: "1"
